spring.application.name=aml-backend

# Neo4j — change password to yours
neo4j.uri=neo4j://127.0.0.1:7687
neo4j.username=neo4j
neo4j.password=neo4j1234

# Python inference service
inference.url=http://localhost:8000

# Server port
server.port=8080

# Show SQL-like logs for debugging
logging.level.com.aml=DEBUG